"""
gen_version.py — PlatformIO pre-build version generator

Reads fw_version.txt (manual semver) and derives the build number from git:
  build = commit_count (always)
  dirty = "-dev" suffix appended when working tree has uncommitted changes

Outputs:
  src/version.h   — C header with #define constants (gitignored)
  version.txt     — plain string read by ESP-IDF for the boot-log App version
"""

import os
import subprocess
import sys

Import("env")  # noqa: F821  (PlatformIO SCons injection)

project_dir = env.subst("$PROJECT_DIR")


def ensure_common_submodule():
    common_dir = os.path.join(project_dir, "common")
    required_dirs = (
        os.path.join(common_dir, "include"),
        os.path.join(common_dir, "hal"),
        os.path.join(common_dir, "src"),
        os.path.join(common_dir, "storage"),
    )

    if all(os.path.isdir(path) for path in required_dirs):
        return

    print("[deps] common/ submodule missing; initializing it via git")
    result = subprocess.run(
        ["git", "submodule", "update", "--init", "--recursive", "common"],
        capture_output=True,
        text=True,
        cwd=project_dir,
    )

    if result.returncode == 0 and all(os.path.isdir(path) for path in required_dirs):
        return

    if result.stdout:
        print(result.stdout.strip())
    if result.stderr:
        print(result.stderr.strip(), file=sys.stderr)

    raise SystemExit(
        "[deps] Failed to initialize required common/ submodule. "
        "Run 'git submodule update --init --recursive common' and retry."
    )


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=project_dir)
    return r.stdout.strip()


ensure_common_submodule()


# --- Read manual semver ---
semver_file = os.path.join(project_dir, "fw_version.txt")
try:
    with open(semver_file) as f:
        semver = f.read().strip()
    parts = semver.split(".")
    major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2])
except Exception as e:
    print(f"[version] WARNING: could not read fw_version.txt ({e}), defaulting to 0.0.0")
    major, minor, patch = 0, 0, 0
    semver = "0.0.0"

# --- Git state ---
commit_count_str = run(["git", "rev-list", "--count", "HEAD"])
commit_hash = run(["git", "rev-parse", "--short", "HEAD"])
dirty_files = run(["git", "status", "--porcelain"])

try:
    commit_count = int(commit_count_str)
except ValueError:
    commit_count = 0

is_dirty = bool(dirty_files)
build_num = commit_count

# --- Build version strings ---
version_str = f"{major}.{minor}.{patch}+{build_num}"
if is_dirty:
    version_str += "-dev"

full_str = f"{version_str} ({commit_hash}{'*' if is_dirty else ''})"

print(f"[version] {full_str}")

# --- Write version.txt (read by ESP-IDF as App version in boot log) ---
with open(os.path.join(project_dir, "version.txt"), "w") as f:
    f.write(version_str + "\n")

# --- Write src/version.h ---
header_path = os.path.join(project_dir, "src", "version.h")
with open(header_path, "w") as f:
    f.write(f"""\
/* Auto-generated by scripts/gen_version.py — do not edit */
#pragma once

#define FW_VERSION_MAJOR   {major}
#define FW_VERSION_MINOR   {minor}
#define FW_VERSION_PATCH   {patch}
#define FW_BUILD_NUMBER    {build_num}
#define FW_BUILD_DIRTY     {1 if is_dirty else 0}
#define FW_COMMIT_HASH     "{commit_hash}{'*' if is_dirty else ''}"
#define FW_VERSION_STRING  "{version_str}"
#define FW_VERSION_FULL    "{full_str}"
""")
