"""
gen_version.py — PlatformIO pre-build version generator

Reads fw_version.txt (manual semver) and derives the build number from git:
  build = commit_count        (clean working tree)
  build = commit_count + 1   (dirty — uncommitted changes present)

Outputs:
  src/version.h   — C header with #define constants (gitignored)
  version.txt     — plain string read by ESP-IDF for the boot-log App version
"""

import subprocess
import os

Import("env")  # noqa: F821  (PlatformIO SCons injection)

project_dir = env.subst("$PROJECT_DIR")


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=project_dir)
    return r.stdout.strip()


# --- Read manual semver ---
semver_file = os.path.join(project_dir, "fw_version.txt")
try:
    with open(semver_file) as f:
        semver = f.read().strip()
    parts = semver.split(".")
    major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2])
except Exception as e:
    print(f"[version] WARNING: could not read fw_version.txt ({e}), defaulting to 0.0.0")
    major, minor, patch = 0, 0, 0
    semver = "0.0.0"

# --- Git state ---
commit_count_str = run(["git", "rev-list", "--count", "HEAD"])
commit_hash = run(["git", "rev-parse", "--short", "HEAD"])
dirty_files = run(["git", "status", "--porcelain"])

try:
    commit_count = int(commit_count_str)
except ValueError:
    commit_count = 0

is_dirty = bool(dirty_files)
build_num = commit_count + (1 if is_dirty else 0)

# --- Build version strings ---
version_str = f"{major}.{minor}.{patch}+{build_num}"
if is_dirty:
    version_str += "-dev"

full_str = f"{version_str} ({commit_hash}{'*' if is_dirty else ''})"

print(f"[version] {full_str}")

# --- Write version.txt (read by ESP-IDF as App version in boot log) ---
with open(os.path.join(project_dir, "version.txt"), "w") as f:
    f.write(version_str + "\n")

# --- Write src/version.h ---
header_path = os.path.join(project_dir, "src", "version.h")
with open(header_path, "w") as f:
    f.write(f"""\
/* Auto-generated by scripts/gen_version.py — do not edit */
#pragma once

#define FW_VERSION_MAJOR   {major}
#define FW_VERSION_MINOR   {minor}
#define FW_VERSION_PATCH   {patch}
#define FW_BUILD_NUMBER    {build_num}
#define FW_BUILD_DIRTY     {1 if is_dirty else 0}
#define FW_COMMIT_HASH     "{commit_hash}{'*' if is_dirty else ''}"
#define FW_VERSION_STRING  "{version_str}"
#define FW_VERSION_FULL    "{full_str}"
""")
